workflows:
  android-apk:
    name: Android APK - GaBoLP
    max_build_duration: 60
    environment:
      flutter: stable

    scripts:
      - name: Preparar proyecto (crear android si falta)
        script: |
          set -e
          echo "PWD: $(pwd)"
          ls -la

          if [ ! -d "android" ]; then
            echo "No existe /android. Generando con flutter create ."

            TMPDIR="$(mktemp -d)"
            echo "TMPDIR=$TMPDIR"

            cp -R lib "$TMPDIR/lib"
            if [ -d "assets" ]; then cp -R assets "$TMPDIR/assets"; fi
            cp pubspec.yaml "$TMPDIR/pubspec.yaml"

            flutter create . --platforms=android --org com.gabolp.app

            rm -f pubspec.yaml
            cp "$TMPDIR/pubspec.yaml" pubspec.yaml

            rm -rf lib
            cp -R "$TMPDIR/lib" lib

            if [ -d "$TMPDIR/assets" ]; then
              rm -rf assets
              cp -R "$TMPDIR/assets" assets
            fi
          fi

      - name: Parche AndroidManifest (permiso INTERNET) - robusto
        script: |
          set -e
          echo "Buscando AndroidManifest.xml..."
          find android -name AndroidManifest.xml -print || true

          MANIFEST="$(find android -name AndroidManifest.xml | head -n 1)"

          if [ -z "$MANIFEST" ]; then
            echo "ERROR: No se encontró AndroidManifest.xml en /android"
            echo "Contenido de /android:"
            ls -la android || true
            exit 1
          fi

          echo "Usando Manifest: $MANIFEST"

          if grep -q "android.permission.INTERNET" "$MANIFEST"; then
            echo "Permiso INTERNET ya existe."
          else
            echo "Agregando permiso INTERNET..."
            # Inserta la línea justo después de la primera línea <manifest ...>
            perl -0777 -i -pe 's/(<manifest[^>]*>)/$1\n    <uses-permission android:name="android.permission.INTERNET"\/>/s' "$MANIFEST"
          fi

          echo "Primeras 40 líneas del Manifest:"
          head -n 40 "$MANIFEST"

      - name: Instalar dependencias
        script: |
          flutter pub get

      - name: Generar Splash
        script: |
          flutter pub run flutter_native_splash:create

      - name: Compilar APK Release
        script: |
          flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
