workflows:
  android-apk:
    name: Android APK - GaBoLP
    max_build_duration: 60
    environment:
      flutter: stable

    scripts:
      - name: Preparar proyecto (crear android si falta)
        script: |
          set -e
          echo "PWD: $(pwd)"
          ls -la

          if [ ! -d "android" ]; then
            echo "No existe /android. Generando con flutter create ."

            TMPDIR="$(mktemp -d)"
            echo "TMPDIR=$TMPDIR"

            # Guardar tus archivos
            cp -R lib "$TMPDIR/lib"
            if [ -d "assets" ]; then cp -R assets "$TMPDIR/assets"; fi
            cp pubspec.yaml "$TMPDIR/pubspec.yaml"

            # Crear estructura Flutter (Android)
            flutter create . --platforms=android --org com.gabolp.app

            # Restaurar tus archivos
            rm -f pubspec.yaml
            cp "$TMPDIR/pubspec.yaml" pubspec.yaml

            rm -rf lib
            cp -R "$TMPDIR/lib" lib

            if [ -d "$TMPDIR/assets" ]; then
              rm -rf assets
              cp -R "$TMPDIR/assets" assets
            fi
          fi

      - name: Parche AndroidManifest (permiso INTERNET)
        script: |
          set -e
          MANIFEST="android/app/src/main/AndroidManifest.xml"

          echo "Buscando Manifest en: $MANIFEST"
          ls -la android/app/src/main || true

          if [ ! -f "$MANIFEST" ]; then
            echo "ERROR: No se encontró AndroidManifest.xml"
            exit 1
          fi

          # Agregar permiso INTERNET si no existe
          if ! grep -q "android.permission.INTERNET" "$MANIFEST"; then
            echo "Agregando permiso INTERNET..."
            # Insertar debajo de la primera línea <manifest ...>
            sed -i.bak '0,/<manifest/{s/<manifest/<manifest>\n    <uses-permission android:name="android.permission.INTERNET"\/>/}' "$MANIFEST"
          else
            echo "Permiso INTERNET ya estaba."
          fi

          echo "Manifest final (primeras 40 líneas):"
          head -n 40 "$MANIFEST"

      - name: Instalar dependencias
        script: |
          flutter pub get

      - name: Generar Splash
        script: |
          flutter pub run flutter_native_splash:create

      - name: Compilar APK Release
        script: |
          flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
