workflows:
  android-apk:
    name: Android APK (GaBoLP)
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
     - name: Preparar proyecto (generar android si falta)
    script: |
      set -e
      if [ ! -d "android" ]; then
        TMPDIR="$(mktemp -d)"
        cp -R lib "$TMPDIR/lib"
        if [ -d "assets" ]; then cp -R assets "$TMPDIR/assets"; fi
        cp pubspec.yaml "$TMPDIR/pubspec.yaml"

        flutter create . --platforms=android --org com.gabolp.app

        rm -f pubspec.yaml
        cp "$TMPDIR/pubspec.yaml" pubspec.yaml

        rm -rf lib
        cp -R "$TMPDIR/lib" lib

        if [ -d "$TMPDIR/assets" ]; then
          rm -rf assets
          cp -R "$TMPDIR/assets" assets
        fi
      fi

  - name: Info Flutter (para debug)
    script: |
      flutter --version
      flutter doctor -v

  - name: Instalar dependencias
    script: |
      flutter pub get

  - name: Verificar assets (muy común que falle por mayúsculas)
    script: |
      ls -la assets || true
      ls -la assets/splash || true

  - name: Analizar código (aquí sale el error REAL)
    script: |
      flutter analyze

  - name: Generar Splash (flutter_native_splash)
    script: |
      flutter pub run flutter_native_splash:create

  - name: Compilar APK Release (verbose)
    script: |
      flutter build apk --release -v
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk

